name: credit_risk
version: "1.0.0"
config-version: 2
profile: credit_risk

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  t0_date: "2025-12-31"   # hypothèse H1

models:
  credit_risk:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
    controles:
      +schema: ctl
      +materialized: view
